export const filterList = [
  'Show All',
  'Chillwave',
  'Vaporwave',
  'Synthwave',
  'New Wave',
  'Retro Wave',
  'Dream Wave',
  'Fashwave',
  'Dark Wave',
  'Ethereal Wave',
  'Cold Wave',
  'Lo-fi',
  'City Pop',
  'Mallsoft',
  'Future Funk',
  'Hardvapour',
  'Witch House',
];
